// Mock data for Talent Service when backend is unavailable
import { TalentDashboard, TalentProject } from './talentService';

export const mockDashboard: TalentDashboard = {
  stats: {
    totalProjects: 5,
    completedProjects: 2,
    ongoingProjects: 3,
    averageRating: 4.5,
    totalSkills: 12,
    totalCertifications: 3,
  },
  recentProjects: [
    {
      id: 1,
      title: 'E-commerce Platform',
      description: 'Build a modern e-commerce website with React and Node.js',
      company: {
        name: 'Tech Solutions Inc',
        logoUrl: undefined,
      },
      technologies: ['React', 'Node.js', 'PostgreSQL', 'Redux'],
      startDate: '2025-01-15',
      endDate: '2025-06-15',
      duration: '5 months',
      budget: 50000000,
      allowancePerStudent: '3,000,000 VNĐ/tháng',
      numberOfStudents: 4,
      spotsAvailable: 1,
      skillRequirements: ['React', 'Node.js', 'Database Design'],
      status: 'RECRUITING',
      memberStatus: 'JOINED',
      memberRole: 'FRONTEND_DEVELOPER',
    },
    {
      id: 2,
      title: 'Mobile Banking App',
      description: 'Develop a secure mobile banking application',
      company: {
        name: 'FinTech Corp',
      },
      technologies: ['Flutter', 'Firebase', 'REST API'],
      startDate: '2025-02-01',
      endDate: '2025-07-31',
      duration: '6 months',
      budget: 75000000,
      allowancePerStudent: '4,000,000 VNĐ/tháng',
      numberOfStudents: 3,
      spotsAvailable: 0,
      skillRequirements: ['Flutter', 'Mobile Development', 'Security'],
      status: 'IN_PROGRESS',
      memberStatus: 'JOINED',
      memberRole: 'MOBILE_DEVELOPER',
    },
  ],
  upcomingTasks: [],
  notifications: [
    'Your project proposal has been approved',
    'New task assigned: Update user interface',
  ],
  profileCompletion: {
    percentage: 75,
    missingFields: ['Portfolio URL', 'LinkedIn URL'],
  },
};

export const mockProjects: TalentProject[] = [
  {
    id: 3,
    title: 'AI Chatbot Development',
    description: 'Create an intelligent chatbot using NLP and machine learning',
    company: {
      name: 'AI Innovations',
    },
    technologies: ['Python', 'TensorFlow', 'NLP', 'Docker'],
    startDate: '2025-03-01',
    endDate: '2025-08-31',
    duration: '6 months',
    budget: 60000000,
    allowancePerStudent: '3,500,000 VNĐ/tháng',
    numberOfStudents: 3,
    spotsAvailable: 2,
    skillRequirements: ['Python', 'Machine Learning', 'NLP'],
    status: 'RECRUITING',
  },
  {
    id: 4,
    title: 'IoT Smart Home System',
    description: 'Build a comprehensive smart home control system',
    company: {
      name: 'Smart Living Co',
    },
    technologies: ['Arduino', 'Raspberry Pi', 'MQTT', 'React'],
    startDate: '2025-02-15',
    endDate: '2025-07-15',
    duration: '5 months',
    budget: 45000000,
    allowancePerStudent: '2,800,000 VNĐ/tháng',
    numberOfStudents: 4,
    spotsAvailable: 3,
    skillRequirements: ['IoT', 'Embedded Systems', 'Web Development'],
    status: 'RECRUITING',
  },
  {
    id: 5,
    title: 'Data Analytics Dashboard',
    description: 'Develop a real-time data visualization dashboard',
    company: {
      name: 'DataViz Corp',
    },
    technologies: ['React', 'D3.js', 'Python', 'FastAPI'],
    startDate: '2025-03-15',
    endDate: '2025-09-15',
    duration: '6 months',
    budget: 55000000,
    allowancePerStudent: '3,200,000 VNĐ/tháng',
    numberOfStudents: 3,
    spotsAvailable: 1,
    skillRequirements: ['React', 'Data Visualization', 'Python'],
    status: 'RECRUITING',
  },
  {
    id: 6,
    title: 'Cloud Infrastructure Migration',
    description: 'Migrate legacy systems to AWS cloud infrastructure',
    company: {
      name: 'CloudTech Solutions',
    },
    technologies: ['AWS', 'Docker', 'Kubernetes', 'Terraform'],
    startDate: '2025-04-01',
    endDate: '2025-10-31',
    duration: '7 months',
    budget: 80000000,
    allowancePerStudent: '4,500,000 VNĐ/tháng',
    numberOfStudents: 5,
    spotsAvailable: 4,
    skillRequirements: ['AWS', 'DevOps', 'Containerization'],
    status: 'RECRUITING',
  },
  {
    id: 7,
    title: 'Blockchain Supply Chain',
    description: 'Implement blockchain for supply chain transparency',
    company: {
      name: 'BlockChain Logistics',
    },
    technologies: ['Ethereum', 'Solidity', 'Web3.js', 'Node.js'],
    startDate: '2025-05-01',
    endDate: '2025-11-30',
    duration: '7 months',
    budget: 90000000,
    allowancePerStudent: '5,000,000 VNĐ/tháng',
    numberOfStudents: 4,
    spotsAvailable: 2,
    skillRequirements: ['Blockchain', 'Smart Contracts', 'Solidity'],
    status: 'RECRUITING',
  },
];
